[package]
name = "zs2_l4_"
version = "0.9.0"
authors = ["zzzzzzzzzzz <zzzzzzzzzzzgg@gmail.com>"]
edition = "2018"

[dependencies]
zhscript2 = {version = "0.9.0", path = "../zhscript2-rust", features = ["thread"]}
libloading = "0.5.0"
rusty-asm = "0.2.1"
regex = "1.3.4"
